# Production configuration file
# @author <a href="https://github.com/Dannywen1213dup">Yifan Wen</a>
# @from <a href="https://www.ai4labos.com/">ai4labOS</a>
server:
  port: 8101
spring:
  # Database configuration
  # todo Need to replace configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
  # Redis configuration
  # todo Need to replace configuration
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch configuration
  # todo Need to replace configuration
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # Disable logging in production environment
    log-impl: ''
# API documentation configuration
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
